### ISSUE TITLE
Archived questions cannot be restored

### ISSUE THREAD

**Issue by H4rryK4ne** [SunyataZero/well-being-diary#45]
There is no possibility to restore an archived question.

**Comment by SunyataZero** [comment]
Good to know, thanks!

**Comment by SunyataZero** [comment]
@H4rryK4ne Okay, this has now been fixed in the latest version

Please note that this is a prototype and you need to remove your old database file to be able to run the application again. If you want to save previous entries you can go to "file -> export" which should give you a csv file with all the diary entries. (Please do this before removing the db file!)

**Comment by SunyataZero** [comment]
To un-archive please click on the "show archived" button and then click the icon that was used for archiving (i'd like to find another icon for this in the future)
